deployment:
  tasks:
    - export DEPLOYPATH=/home2/dimaggio/public_html/
    - /bin/cp dpw-blackboard-menus.html $DEPLOYPATH
    - /bin/cp index.css $DEPLOYPATH
    - /bin/cp media.css $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    # - /bin/cp -R images $DEPLOYPATH
